name: logging_appenders
description: Logging appenders for the dart logging package for print, file and remote (logz, loki).
version: 1.1.0
homepage: https://github.com/hpoul/dart_logging_appenders/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ">=1.3.0 <2.0.0"
  logging: '>=1.2.0 <2.0.0'
  dio: ">=4.0.0 <6.0.0"
  intl: ">=0.17.0 <1.0.0"
  clock: ">=1.1.0 <2.0.0"
  path: ">=1.1.0 <2.0.0"

dev_dependencies:
  test: ^1.23.1
  lints: ^2.0.1
  mockito: ^5.3.2
  fake_async: ^1.3.1
  build_runner: ^2.3.3
